# Generated by Django 2.2.5 on 2019-12-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('Adultid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('workclass', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('race', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('hours_per_week', models.FloatField(blank=True, default=None, null=True)),
                ('income', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'adult',
            },
        ),
        migrations.CreateModel(
            name='AdultCFk_3',
            fields=[
                ('Adultid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('workclass', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('race', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('hours_per_week', models.FloatField(blank=True, default=None, null=True)),
                ('income', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'adultcfk_3',
            },
        ),
        migrations.CreateModel(
            name='AdultCFk_4',
            fields=[
                ('Adultid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('workclass', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('race', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('hours_per_week', models.FloatField(blank=True, default=None, null=True)),
                ('income', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'adultcfk_4',
            },
        ),
        migrations.CreateModel(
            name='AdultCFk_5',
            fields=[
                ('Adultid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('workclass', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('race', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('hours_per_week', models.FloatField(blank=True, default=None, null=True)),
                ('income', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'adultcfk_5',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LIMEexp',
            fields=[
                ('Adultid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('workclass', models.FloatField(blank=True, default=None, null=True)),
                ('education', models.FloatField(blank=True, default=None, null=True)),
                ('marital_status', models.FloatField(blank=True, default=None, null=True)),
                ('occupation', models.FloatField(blank=True, default=None, null=True)),
                ('race', models.FloatField(blank=True, default=None, null=True)),
                ('gender', models.FloatField(blank=True, default=None, null=True)),
                ('hours_per_week', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_choice1', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')])),
                ('rate_choice2', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')])),
                ('rate_choice3', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')])),
                ('rate_choice4', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')])),
                ('rate_choice5', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')])),
            ],
        ),
    ]
