# Generated by Django 2.2.5 on 2020-03-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('Adultid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('workclass', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('race', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('hours_per_week', models.FloatField(blank=True, default=None, null=True)),
                ('income', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'adult',
            },
        ),
        migrations.CreateModel(
            name='AdultCFk_3',
            fields=[
                ('Adultid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('workclass', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('race', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('hours_per_week', models.FloatField(blank=True, default=None, null=True)),
                ('income', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'adultcfk_3',
            },
        ),
        migrations.CreateModel(
            name='AdultCFk_4',
            fields=[
                ('Adultid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('workclass', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('race', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('hours_per_week', models.FloatField(blank=True, default=None, null=True)),
                ('income', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'adultcfk_4',
            },
        ),
        migrations.CreateModel(
            name='AdultCFk_5',
            fields=[
                ('Adultid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('workclass', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('race', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('hours_per_week', models.FloatField(blank=True, default=None, null=True)),
                ('income', models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'adultcfk_5',
            },
        ),
        migrations.CreateModel(
            name='LIMEexp',
            fields=[
                ('Adultid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('age', models.FloatField(blank=True, default=None, null=True)),
                ('workclass', models.FloatField(blank=True, default=None, null=True)),
                ('education', models.FloatField(blank=True, default=None, null=True)),
                ('marital_status', models.FloatField(blank=True, default=None, null=True)),
                ('occupation', models.FloatField(blank=True, default=None, null=True)),
                ('race', models.FloatField(blank=True, default=None, null=True)),
                ('gender', models.FloatField(blank=True, default=None, null=True)),
                ('hours_per_week', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'survey_comments',
            },
        ),
        migrations.CreateModel(
            name='Survey_rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_choice1', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')])),
                ('rate_choice2', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')])),
                ('rate_choice3', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')])),
                ('rate_choice4', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')])),
                ('rate_choice5', models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '')])),
            ],
            options={
                'db_table': 'Survey_rates',
            },
        ),
        migrations.CreateModel(
            name='Survey_result',
            fields=[
                ('dataid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('workid', models.IntegerField(blank=True, default=None, null=True)),
                ('testcase_1', models.IntegerField(blank=True, default=None, null=True)),
                ('testcase_2', models.IntegerField(blank=True, default=None, null=True)),
                ('testcase_3', models.IntegerField(blank=True, default=None, null=True)),
                ('true_1', models.IntegerField(blank=True, default=None, null=True)),
                ('true_2', models.IntegerField(blank=True, default=None, null=True)),
                ('true_3', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'survey_result',
            },
        ),
    ]
